planner_configs:
  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
    range: 0.15
    intermediate_states: true

arm:
  default_planner_config: RRTConnectkConfigDefault
  planner_configs:
    - RRTConnectkConfigDefault
  projection_evaluator: joints(panda_joint1,panda_joint2)
  longest_valid_segment_fraction: 0.002
